heat_template_version: 2015-04-30

description: rack level affinity - basic - 5 instances

resources:

  my-instance-1:
    type: OS::Nova::Server
    properties:
      name: test-1
    #  key_name: ssh-key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
     # networks:
      #  - network: 0c405776-0c37-4212-a814-e8aa539b32b5

  my-instance-2:
    type: OS::Nova::Server
    properties:
      name: test-2
      #key_name: ssh-key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
      #networks:
       # - network: 0c405776-0c37-4212-a814-e8aa539b32b5

  my-instance-3:
    type: OS::Nova::Server
    properties:
      name: test-3
     # key_name: ssh-key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
     # networks:
       # - network: 0c405776-0c37-4212-a814-e8aa539b32b5

  my-instance-4:
    type: OS::Nova::Server
    properties:
      name: test-4
    #  key_name: ssh-key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
     # networks:
      #  - network: 0c405776-0c37-4212-a814-e8aa539b32b5

  my-instance-5:
    type: OS::Nova::Server
    properties:
      name: test-5
      #key_name: ssh-key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
      #networks:
       # - network: 0c405776-0c37-4212-a814-e8aa539b32b5

  test-affinity-group14:
    type: ATT::Valet::GroupAssignment
    properties:
      group_type: affinity
      level: rack
      resources:
      - {get_resource: my-instance-1}
      - {get_resource: my-instance-2}
      - {get_resource: my-instance-3}
      - {get_resource: my-instance-4}
      - {get_resource: my-instance-5}
 
outputs:
  instance_ip-1:
    description: The IP addresses of the deployed instance 1
    value: { get_attr: [my-instance-1, first_address] }
  instance_ip-2:
    description: The IP addresses of the deployed instance 2
    value: { get_attr: [my-instance-2, first_address] }
  instance_ip-3:
    description: The IP addresses of the deployed instance 3
    value: { get_attr: [my-instance-3, first_address] }
  instance_ip-4:
    description: The IP addresses of the deployed instance 4
    value: { get_attr: [my-instance-4, first_address] }
  instance_ip-5:
    description: The IP addresses of the deployed instance 5
    value: { get_attr: [my-instance-5, first_address] }
