heat_template_version: 2013-05-23

description: Nested Stack

parameters:
  server_image:
    type: string
    description: Image used for the servers
    default: Fedora-x86_64-20-20131211.1-sda
  server_flavor:
    type: string
    description: Flavor used by the servers
    default: m1.small
  ssh_key:
    type: string
    description: SSH key to connect to the servers
    default: demo
  preferred_server_az:
    type: string
    description: Preferred server availability zone
    default: nova

  #
  # NOTE: There are named versions of these post-Icehouse. No _id needed!
  #
  public_net_id:
    type: string
    description: ID of public net for which floating IPs will be allocated
    default: 0881c3f0-5cda-4220-9d8a-59b90556e57f
  private_net_id:
    type: string
    description: ID of private network into which servers get deployed
    default: a4ea3546-4b4c-43c7-b6f3-752a058ca9bb
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
    default: a3c56a42-e019-4643-8eaf-a760a2914857
    
resources:
  server:
    type: OS::Nova::Server
    properties:
      name: server
      flavor: {get_param: server_flavor}
      image: {get_param: server_image}
      key_name: {get_param: ssh_key}
      availability_zone: {get_param: preferred_server_az}
      networks:
      - port: {get_resource: server_port}

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: private_net_id}
      fixed_ips:
      - subnet_id: {get_param: private_subnet_id}

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: public_net_id}
      port_id: {get_resource: server_port}

outputs:
  server_all:
    description: All server info
    value: {get_attr: [server, show]}
