heat_template_version: 2015-04-30

description: Host aggregate and affinity template - both VMs should end up on the same host

resources:

  my-instance-1:
    type: OS::Nova::Server
    properties:
      name: test-1
      #key_name: my_key
      image: cirros-0.3.4-x86_64
      flavor: m1.HA1 
      #networks:
       # - network: bigsite-public 

  my-instance-2:
    type: OS::Nova::Server
    properties:
      name: test-2
      #key_name: my_key
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny 
      #networks:
      #  - network: bigsite-public 

  my-affinity-group111:
    type: ATT::Valet::GroupAssignment
    properties:
      group_type: affinity
      level: host
      resources:
      - {get_resource: my-instance-1}
      - {get_resource: my-instance-2}
  
outputs:
  instance_ip-1:
    description: The host of the deployed instance 1
    value: {get_attr: [my-instance-1, show, 'OS-EXT-SRV-ATTR:host']}
  instance_ip-2:
    description: The host of the deployed instance 2
    value: {get_attr: [my-instance-2, show, 'OS-EXT-SRV-ATTR:host']}
